angular.module('admin',['ngRoute','admin-controller'])
	.controller('adminNameCtrl',function($scope){
		/*-------------展开与隐藏二级菜单开始-------------*/
		$('.child-menu-par').click(function(){
			var $sbilingItem=$(this).next();
			var $iconItem=$(this).children();
			var num=$(this).attr('data-id');
			//二级菜单进行折叠的函数
			var fold=function($aimElem,$aimIcon){
				$aimElem.slideUp();
				$aimIcon.css('background-image','url("./images/down-arrow.png")');
				$aimElem.removeClass('open');
			};
			switch(num){
				case '1':
					//让非信息统计折叠
					fold($('.recom-items'),$('.arrIcon-two'));
					fold($('.order-items'),$('.arrIcon-three'));
					fold($('.grade-items'),$('.arrIcon-four'));
					fold($('.admin-items'),$('.arrIcon-five'));
					break;
				case '2':
					//让非书籍推荐折叠
					fold($('.info-items'),$('.arrIcon-one'));
					fold($('.order-items'),$('.arrIcon-three'));
					fold($('.grade-items'),$('.arrIcon-four'));
					fold($('.admin-items'),$('.arrIcon-five'));
					break;
				case '3':
					//让非订单查询折叠
					fold($('.info-items'),$('.arrIcon-one'));
					fold($('.recom-items'),$('.arrIcon-two'));
					fold($('.grade-items'),$('.arrIcon-four'));
					fold($('.admin-items'),$('.arrIcon-five'));
					break;
				case '4':
					//让非级别评定折叠
					fold($('.info-items'),$('.arrIcon-one'));
					fold($('.recom-items'),$('.arrIcon-two'));
					fold($('.order-items'),$('.arrIcon-three'));
					fold($('.admin-items'),$('.arrIcon-five'));
					break;
				case '5':
					//让非管理书籍类别折叠
					fold($('.info-items'),$('.arrIcon-one'));
					fold($('.recom-items'),$('.arrIcon-two'));
					fold($('.order-items'),$('.arrIcon-three'));
					fold($('.grade-items'),$('.arrIcon-four'));
					break;
			}
			if($sbilingItem.hasClass('open')){
				//当当前点击元素是展开的时候
				$sbilingItem.slideUp();
				$iconItem.css('background-image','url("./images/down-arrow.png")');
				$sbilingItem.removeClass('open');
			}else{
				$sbilingItem.slideDown();
				$iconItem.css('background-image','url("./images/up-arrow.png")');
				$sbilingItem.addClass('open');
			}	
		});
		/*-------------展开与隐藏二级菜单结束-------------*/

		/*----根据商家点击不同的选项，高亮不同的条目并在右边显示不同的内容开始---*/
		$('.left-menus a').click(function(){
			var num=$(this).attr('data-id');
			$('.left-menus a').removeClass('height-left-mean');
			if(num!='1'&&num!='2'){
				$(this).addClass('height-left-mean');
			}else{
				//此时点击的是我的信息
				$('.my-info').addClass('height-left-mean');
			}
		});
		/*----根据商家点击不同的选项，高亮不同的条目并在右边显示不同的内容结束---*/
	})
	.config(function($routeProvider){
		$routeProvider
			.when('/saleroom',{
				templateUrl:'view/admin/saleroom.html',
				controller:'saleroomCtrl'
			})
			.when('/customerRegNum',{
				templateUrl:'view/admin/customerRegNum.html',
				controller:'customerRegNumCtrl'
			})
			.when('/sellerRegNum',{
				templateUrl:'view/admin/sellerRegNum.html',
				controller:'sellerRegNumCtrl'
			})
			.when('/hotBook',{
				templateUrl:'view/admin/hotBook.html',
				controller:'hotBookCtrl'
			})
			.when('/weSearch',{
				templateUrl:'view/admin/weSearch.html',
				controller:'weSearchCtrl'
			})
			.when('/weSpeak',{
				templateUrl:'view/admin/weSpeak.html',
				controller:'weSpeakCtrl'
			})
			.when('/allOrder',{
				templateUrl:'view/admin/allOrder.html',
				//controller:'allOrderCtrl'
			})
			.when('/waitSend',{
				templateUrl:'view/admin/waitSend.html',
				//controller:'waitSendCtrl'
			})
			.when('/waitGoods',{
				templateUrl:'view/admin/waitGoods.html',
				//controller:'waitGoodsCtrl'
			})
			.when('/waitRecom',{
				templateUrl:'view/admin/waitRecom.html',
				//controller:'waitRecomCtrl'
			})
			.when('/accessShop',{
				templateUrl:'view/admin/accessShop.html',
				controller:'accessShopCtrl'
			})
			.when('/accessBook',{
				templateUrl:'view/admin/accessBook.html',
				controller:'accessBookCtrl'
			})
			.when('/editSmCate',{
				templateUrl:'view/admin/editSmCate.html',
				controller:'editSmCateCtrl'
			})
			.when('/addSmCate',{
				templateUrl:'view/admin/addSmCate.html',
				controller:'addSmCateCtrl'
			})
			.when('/welcome',{
				templateUrl:'view/admin/welcome.html',
				//controller:'welcomeCtrl'
			})
			.otherwise({redirectTo:'/welcome'});
	});